### ISSUE TITLE
IoTSharp.Edge.ModBus 不能迁移至 .net core 3.0

### ISSUE THREAD

**Issue by lable** [IoTSharp/IoTSharp#13]
难道是因为 Quartzmin 不支持 .net core 3.0 ?

**Comment by maikebing** [comment]
Quartzmin  不好用， 打算废掉了。 

IoTSharp.Edge.ModBus 使用的HSL组件已经闭源了， 在考虑后面是不是要删掉

**Comment by lable** [comment]
HSL算是做得比较强大了，还有更好的选择吗？

**Comment by maikebing** [comment]
最近在关注。 找一个合适的， 作为接替者  ,IoTSharp.Edge.ModBus  我打算单独弄出来作为 对接案例
