### ISSUE TITLE
问一下，这个库为啥没有做nuget发布？至少核心库应该发nuget

### ISSUE THREAD

**Issue by tonyqus** [IoTSharp/IoTSharp#156]
如题

**Comment by maikebing** [comment]
这个不是库， 是专门部署的。独立应用。

**Comment by tonyqus** [comment]
我知道呀，但没有拆分不同的dll吗？其实有些dll可以放nuget里面，剩下的壳单独部署就行了。

**Comment by maikebing** [comment]
有一部分拆了。 比如X509 证书之类的

**Comment by tonyqus** [comment]
所以这个是你的包咯？https://www.nuget.org/packages/IoTSharp.X509Extensions/，我还以为只是同名呢

**Comment by maikebing** [comment]
https://www.nuget.org/packages/IoTSharp.CoAP.NET/ 
https://www.nuget.org/packages/IoTSharp.Sdk.Http/

**Comment by maikebing** [comment]
https://www.nuget.org/packages/IoTSharp.Sdk.MQTT/
https://www.nuget.org/packages/IoTSharp.Extensions.AspNetCore/

**Comment by tonyqus** [comment]
了解
