### ISSUE TITLE
有没有docker运行教程的

### ISSUE THREAD

**Issue by qcjxberin** [IoTSharp/IoTSharp#246]
有没有docker运行教程的,
下载下来之后直接运行报错。

**Comment by maikebing** [comment]
https://github.com/IoTSharp/IoTSharp/tree/master/Deployments   
看看这个目录下 docker-compose

**Comment by qcjxberin** [comment]
还是不知道具体应该怎么部署弄，能不能弄个教程以减少入手门槛的

**Comment by maikebing** [comment]
2021年会加入一些 教程。

**Comment by maikebing** [comment]
可以考虑 关注我们公众号。  
![貔貅物联网公众号](../raw/master/docs/images/qrcode.jpg)

我们会不定期发布一些文章。
