### ISSUE TITLE
datastorage和telemetrydata中部分数据字段的是否应允许为空

### ISSUE THREAD

**Issue by rennner** [IoTSharp/IoTSharp#332]
以下字段默认为非空：
Value_Boolean、Value_Long、Value_DateTime、Value_Double
是否考虑设置为可空，同时实体类设置为类型bool?等。

解决问题：不同数据库的字段例如TIMESTAMP最小值可能不同，例如mysql就无法保存"0-0-0 0:0:0" 
如果不允许为空，则必须设置一个值，反而更麻烦。

**Comment by maikebing** [comment]
恩， 可以。 确实是。
