### ISSUE TITLE
vue客户端不能运行

### ISSUE THREAD

**Issue by lable** [IoTSharp/IoTSharp#395]
**Describe the bug**
最新代码运行 npm run serve报错

**To Reproduce**
npm run serve

**Expected behavior**
error: Unexpected trailing comma (comma-dangle) at src\views\user\Register.vue:306:6:
  304 |     'state.passwordLevel'(val) {
  305 |       console.log(val)
> 306 |     },
      |      ^
  307 |   },
  308 | }
  309 | </script>

error: Unexpected trailing comma (comma-dangle) at src\views\user\Register.vue:307:4:
  305 |       console.log(val)
  306 |     },
> 307 |   },
      |    ^
  308 | }
  309 | </script>
  310 | <style lang="less">

23 errors and 1 warning found.
23 errors and 1 warning potentially fixable with the `--fix` option.

 @ ./src/config/router.config.js 542:13-544:30
 @ ./src/store/modules/permission.js
 @ ./src/store/index.js
 @ ./src/core/directives/action.js
 @ ./src/core/lazy_use.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.0.20:8000&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by maikebing** [comment]
已经升级为vue3 了。
