### ISSUE TITLE
docker-compose 启动 rabbit_mongo_influx 创建设备失败

### ISSUE THREAD

**Issue by iioter** [IoTSharp/IoTSharp#585]
An error occurred while saving the entity changes. See the inner exception for details.\n ---\u003E System.InvalidCastException: Cannot write DateTime with Kind=Local to PostgreSQL type \u0027timestamp with time zone\u0027, only UTC is supported. Note that it\u0027s not possible to mix DateTimes with different Kinds in an array/range. See the Npgsql.EnableLegacyTimestampBehavior AppContext switch to enable legacy behavior.

我提交过一次pr，源码启动已经解决了这个问题，可能docker镜像的版本没有合并？

            AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);
            AppContext.SetSwitch("Npgsql.DisableDateTimeInfinityConversions", true);

**Comment by maikebing** [comment]
镜像  可能不是最新的。  我记得我测过来着。

**Comment by maikebing** [comment]
升级为最新 ef 6  也解决。
