### ISSUE TITLE
数据断面聚合

### ISSUE THREAD

**Issue by maikebing** [IoTSharp/IoTSharp#658]
需求
一天内  一万条数据， 整合成一小时一条， 使用平均的方法， 或者每个小时的最后一条作为依据。 
Task<List<TelemetryDataDto>> LoadTelemetryAsync(Guid deviceId, string keys, DateTime begin, DateTime end, TimeSpan every, Aggregate aggregate);

注意
keys 为空则表示全部， 
every 如果是 TimeSpan.Zero表示不适用。aggregate 也不会使用。 

- [x] #802
- [x] #803
- [x] #804
- [x] InfluxDBStorage    已实现。 
- [x] #805
- [x] #806
- [x] IoTDB   已实现

**Comment by maikebing** [comment]
InfluxDB 中的语法。 
```
from(bucket: "iotsharp")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "TelemetryData")
  |> filter(fn: (r) => r["DeviceId"] == "52958d0c-c462-4644-b91f-a0c4587f898e")
  |> filter(fn: (r) => r["_field"] == "humidity")
  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)
  |> yield(name: "mean")
```

**Comment by maikebing** [comment]
![image](https://user-images.githubusercontent.com/3445167/159529579-1d73b741-b949-4a75-8d7d-c016308c43f1.png)

**Comment by maikebing** [comment]
IoTDB 已经实现。 
https://github.com/IoTSharp/IoTSharp/pull/726

**Comment by maikebing** [comment]
修复跟 InfluxDB有关的bug  https://github.com/IoTSharp/IoTSharp/pull/770

**Comment by iotbi** [comment]
TimescaleDB实现了么

**Comment by maikebing** [comment]
TimescaleDB 没实现呢。
