### ISSUE TITLE
设备遥测历史趋势图显示

### ISSUE THREAD

**Issue by iioter** [IoTSharp/IoTSharp#692]
- 设备=>遥测=>历史=>图表

![d5ac8834a35db79f124da1f1233ceec](https://user-images.githubusercontent.com/29589505/165711860-11589580-b697-4f4e-ac96-c924b8b4ae93.png)

- 时间无法显示年、时分秒等
![59e2165f956acef5d2950afe9e0721a](https://user-images.githubusercontent.com/29589505/165711811-48febee2-c1d0-4338-a1b9-442df3ed3c00.png)
![689eac5d6224fb474946d05da0d24f7](https://user-images.githubusercontent.com/29589505/165711836-42a3ce0b-80ba-43b3-9011-c5bdb078dbac.png)

- delon的组件bug？

**Comment by maikebing** [comment]
我们遇到一个问题， 有时候直接页面会崩掉。 不知道你遇到过没

**Comment by maikebing** [comment]
错误代码: STATUS_BREAKPOINT
