### ISSUE TITLE
按照步骤，linux里跑不起来，报错

### ISSUE THREAD

**Issue by Dahe2008** [IoTSharp/IoTSharp#75]
centos里按照教程执行：
mkdir /var/lib/iotsharp/
cp ./* /var/lib/iotsharp/
chmod 777 /var/lib/iotsharp/IoTSharp
cp iotsharp.service /etc/systemd/system/iotsharp.service
sudo systemctl enable /etc/systemd/system/iotsharp.service
sudo systemctl start iotsharp.service
sudo journalctl -fu iotsharp.service

### 报错！！！:“failed at step USER spawning /var/lib/iotsharp/IoTSharp: No such process”

http://127.0.0.1:80/

**Comment by maikebing** [comment]
https://stackoverflow.com/questions/43579534/kestrel-hellomvc-service-failed-at-step-user-spawning-usr-bin-dotnet-no-such 
两个可能， 一个是文件夹没权限， 不是755 。 另外， 本地 80端口好像如果不是  管理员用户  不能使用 80

**Comment by maikebing** [comment]
看用户服务的权限 查看  
https://github.com/IoTSharp/IoTSharp/blob/fb6b51459eebc929361b8ef6c9d06e1e9a8fc92b/IoTSharp/iotsharp.service#L12
