### ISSUE TITLE
网关与IotSharp的Broker应该通过KeepAlive判断是否断开连接

### ISSUE THREAD

**Issue by wangmh2003** [IoTSharp/IoTSharp#796]
现在IotSharp是通过网关最后上报数据的时间与现有时间比较，如果超过一定时间就认为网关离线。这种机制会造成网关的MQTT连接频繁被断开。合理的方式是通过KeepAlive设置的时间来处理，一般网关默认的KeepAlive时间是60秒，每到60秒会发送Ping进行保活。

**Comment by maikebing** [comment]
我调整为了下面的方式：
所有在线且活跃时间超时的设备如果不在已连接客户端内， 则认为是离线。 
这里的子设备我们认为是有链接的设备， 而不是无连接的。
