### ISSUE TITLE
设备管理查询

### ISSUE THREAD

**Issue by OweQian** [IoTSharp/IoTSharp#810]
/api/Devices/Customers
缺少字段
![image](https://user-images.githubusercontent.com/25632596/194767938-e6088e6a-a9df-44fb-b756-a72a2d937ec3.png)

**Comment by maikebing** [comment]
`{"data":{"total":1,"rows":[{"id":"2c3586a0-6c6e-41da-89cc-6fb242e7a2d6","name":"chineseworkd","deviceType":"Device","timeout":300,"owner":null,"identityType":"AccessToken","identityValue":null,"identityId":"03072519c34944c8bc89c12f5db07e6c","active":false,"lastActivityDateTime":null,"tenantName":"iotmaster@iotsharp.net","customerName":"iotmaster@iotsharp.net","tenantId":"e1ee19de-d60e-4352-8ab9-4b4fcb62eded","customerId":"f1adab49-b53d-4387-8756-4147edc04f26"}],"hasNextPageData":false},"code":10000,"msg":"OK"}`

**Comment by maikebing** [comment]
"active": false,  活动
"lastActivityDateTime": null,  最后活动时间
