### ISSUE TITLE
这么个好的仓库为什么不花点时间写个好的教程或手册

### ISSUE THREAD

**Issue by dsp6414** [IoTSharp/IoTSharp#826]
软件文档让人一头雾水，既对直接使用者不友好也让二次开发者一脸懵逼。

**Comment by maikebing** [comment]
人力不足啊。

**Comment by dsp6414** [comment]
商汤的mmdetection,facebookResearch的pytorch哪个不是因为有完善的手册而大火。微软为啥经久不衰，就是因为它把用户当上帝。😄

**Comment by maikebing** [comment]
个人开源， 财力 物力  人力 优先 ， 基本靠大家资源。 没有办法啊。

**Comment by maikebing** [comment]
目前文档可以 看下  https://docs.iotsharp.net/

**Comment by maikebing** [comment]
如果有兴趣 ， 可以考虑加入我们， 帮我们完善手册。
