### ISSUE TITLE
求助:设备可以连接，但不能获得遥测数据

### ISSUE THREAD

**Issue by dsp6414** [IoTSharp/IoTSharp#845]
appsetting.Development.json:

{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "-IoTSharp.Handlers.MQTTServerHandler": "Warning",
      "-MaiKeBing.CAP.ZeroMQ.ZeroMQTransport": "Warning",
      "-MQTTnet.Diagnostics.IMqttNetLogger": "Warning",
      "-DotNetCore.CAP.Internal.ConsumerRegister": "Warning",
      "-DotNetCore.CAP.Internal.SubscribeDispatcher": "Warning",
      "-DotNetCore.CAP.Internal.SubscribeInvoker": "Warning"
    }
  },
  "ConnectionStrings": {
    "IoTSharp": "Server=pgsql;Database=IoTSharp1;Username=postgres;Password=future;Pooling=true;MaxPoolSize=1024;",
    "EventBusStore": "mongodb://root:kissme@mongodb:27017",
    "TelemetryStorage": "http://110.42.224.209:8086/?org=iotsharp_ccnu&bucket=iotsharp_ccnu_bucket&token=00ScZA6QJgCYerIJoQD0nPHG-1H9wBcfnqV5yzN4_ZAQ-zluyI9PeIt2EKQ1XHZKHMLMyJXuK0tSp1qL2M-Zhw==&&latest=-72h",
    "EventBusMQ": "amqp://root:kissme@rabbitmq:5672"
  },
  "JwtKey": "kissmekissmekissmekissmekissmekissmekissmekissmekissmekissmekissmekissmekissmekissmekissmekissme",
  "JwtExpireHours": 24,
  "JwtIssuer": "IoTSharp.Net",
  "JwtAudience": "IoTSharp.Net",
  "EventBusStore": "MongoDB",
  "EventBusMQ": "RabbitMQ",
  "TelemetryStorage": "InfluxDB",
  "ConsumerThreadCount": 10,
  "DbContextPoolSize": 256,
  "-Discovery": {
    "DiscoveryServerHostName": "consul",
    "DiscoveryServerPort": 8500,
    "CurrentNodeHostName": "iotsharp",
    "CurrentNodePort": 5800,
    "NodeId": 1,
    "NodeName": "iotsharp"
  }
}

前端代码如下:
using MQTTnet;
using MQTTnet.Client;
using MQTTnet.Client.Options;
using Newtonsoft.Json;
using System;
using System.Threading.Tasks;

namespace MQTTClient
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            MQTTnet.MqttFactory factory = new MQTTnet.MqttFactory();
            var client = factory.CreateMqttClient();
            var options = new MqttClientOptionsBuilder()
                        .WithClientId(Guid.NewGuid().ToString())
                        .WithTcpServer("110.42.224.209")
                        .WithCredentials("52a7e5446c3b4d73b23e24c93b95d710", "")//token
                        .Build();
         client.UseApplicationMessageReceivedHandler(ax=>
         {
             Console.WriteLine($"ClientId{ ax.ClientId},msg={ax.ApplicationMessage.ConvertPayloadToString()}");
         });
      
            Task.Run(async () =>
            {
                await client.ConnectAsync(options);
                var random = new Random();
                do
                {
                    var message = new MqttApplicationMessageBuilder()
                                   .WithTopic("/devices/pisys_01/telemetry")
                                   .WithPayload(JsonConvert.SerializeObject(new
                                   {
                                       temp = random.Next(),
                                       NowTime = DateTime.Now
                                   }))
                                   .Build();
                    Console.WriteLine(message.ConvertPayloadToString());
                    await client.PublishAsync(message);
                    await Task.Delay(TimeSpan.FromSeconds(10));

                } while (Console.ReadKey().Key != ConsoleKey.Escape);
                await client.DisconnectAsync();
            }).Wait();
        }
    }
}

设备可以连接上，但无法获得遥测数据，不知道哪里设置错了。

**Comment by dsp6414** [comment]
感觉程序停在这里
await client.PublishAsync(message);

**Comment by maikebing** [comment]
如果设备 52a7e5446c3b4d73b23e24c93b95d710 是网关， 你发的 "/devices/pisys_01/telemetry"  没问题， 
如果是  普通设备，则需要改成   "/devices/me/telemetry"

**Comment by dsp6414** [comment]
pisys_01是普通设备名，me是不是就是pisys_01

**Comment by dsp6414** [comment]
不用设备名pisys_01是吧，谢谢，我再试试。

**Comment by maikebing** [comment]
是的。
