### ISSUE TITLE
菜单名称显示异常

### ISSUE THREAD

**Issue by wacoom** [IoTSharp/IoTSharp#945]
一级菜单和第一个二级菜单的路径相同导致二级菜单的名称在 tagView 显示异常
<img width="1442" alt="image" src="https://user-images.githubusercontent.com/656991/207273546-2bb9ac7e-1b71-40ce-990c-86722e5e2e7c.png">
<img width="489" alt="image" src="https://user-images.githubusercontent.com/656991/207273955-1843e8ab-67c2-4131-98de-5a853987cc16.png">

**Comment by wacoom** [comment]
https://github.com/IoTSharp/IoTSharp/blob/d33c6a497fb58adb3e27ef3f792e9af541ebfed6/IoTSharp/Controllers/MenuController.cs

**Comment by maikebing** [comment]
已经完成。
