### ISSUE TITLE
报”按月分表时间至少大于当前时间一个月“错误

### ISSUE THREAD

**Issue by fzlinsj** [IoTSharp/IoTSharp#970]
使用Sqlite 为数据存储 方式进行Window中部署的时候出上述错误（时间是2023－1－31：15：00 左右），后偶然发现如果把时间的日期修改成（2023－1－25：15：00），上述错误消失（可正常运行）。

**Comment by maikebing** [comment]
@xuejmnet

**Comment by xuejmnet** [comment]
@fzlinsj 具体错误是这个吗能否发一下异常信息

**Comment by xuejmnet** [comment]
@maikebing 
![image](https://user-images.githubusercontent.com/18061232/216769314-6d67b270-b77e-44ff-a508-4d22ad511a10.png)
https://github.com/IoTSharp/IoTSharp/blob/6a9471cfcfd892430b81ef63b193e826caebb37c/IoTSharp.Data.TimeSeries/DependencyInjection.cs#L52

**Comment by maikebing** [comment]
啊。 是我的问题
