### ISSUE TITLE
MemoryCache缓存使用报错

### ISSUE THREAD

**Issue by jimojiangdahu** [IoTSharp/IoTSharp#982]
新建规则链，通过c#脚本计算乘方
![image](https://user-images.githubusercontent.com/20805685/222364977-f96ec2f1-ded8-439d-928c-82afa260f841.png)
发送数据并测试
![image](https://user-images.githubusercontent.com/20805685/222365045-d3a27114-62f5-4850-84fd-7ee6e11a9c80.png)
直接抛出异常，报"Cache entry must specify a value for Size when SizeLimit is set."
![image](https://user-images.githubusercontent.com/20805685/222365116-28986546-f1cd-45b8-b609-7dfd0a04cdb5.png)
报错是因为C#脚本执行引擎里面用到了MemoryCache缓存
![image](https://user-images.githubusercontent.com/20805685/222365344-458c0f98-1416-4ecc-9f17-ac6693044c0d.png)
根据官方文档的说法，如果缓存整体设置了size，则每个缓存entry在创建时也必须指定size
https://learn.microsoft.com/zh-cn/aspnet/core/performance/caching/memory?view=aspnetcore-7.0
![image](https://user-images.githubusercontent.com/20805685/222365653-bee10115-2e55-4eab-889c-133b6bedc464.png)
通过调试发现，在依赖注入缓存对象时，默认的缓存SizeLimit大小是10240
![image](https://user-images.githubusercontent.com/20805685/222365729-a1afc4ab-36cf-49d1-9ba0-554f4380e068.png)
而根据官方说法"在缓存上设置大小限制时，所有条目在添加时都必须指定大小"，可以推测出，报异常是因为依赖注入设置了默认的缓存大小限制，但框架保存缓存条目时，没有设置条目大小导致的异常。
通过查看MemoryCache缓存源码，可以印证猜测：
https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Caching.Memory/src/MemoryCache.cs
![image](https://user-images.githubusercontent.com/20805685/222366121-b8559c74-0ec1-4dd4-9367-4f8b9e3fe6cf.png)
加入一行设置Entry大小的代码
![image](https://user-images.githubusercontent.com/20805685/222366189-7283a8ae-7d53-4109-a27e-6313b59fa6fc.png)
![image](https://user-images.githubusercontent.com/20805685/222366224-2227377e-abe7-4dc2-8799-912c24a4c900.png)

**Comment by maikebing** [comment]
在你测试过程中， 感觉有咩有必要  这里 用 MemoryCache ，

**Comment by jimojiangdahu** [comment]
> 在你测试过程中， 感觉有咩有必要 这里 用 MemoryCache ，
我没有做性能测试，但是在实际场景中，设备传过来的数据是会有时间间隔的，同一规则链脚本代码触发也有一定间隔，
所以这里不做缓存应该也可以。 如果实际遇到了性能瓶颈，也可以再加上

**Comment by maikebing** [comment]
你建议怎么改？要不提个PR?

**Comment by maikebing** [comment]
好纠结。

**Comment by jimojiangdahu** [comment]
> 你建议怎么改？要不提个PR?

我回去再研究下

**Comment by jimojiangdahu** [comment]
测试了一下基于.net 7的iotsharp，不存在此问题。  应该是官方已经修复了缓存SizeLimit默认值为10240的那个问题

**Comment by maikebing** [comment]
好。
